version: "3.7"

services:
  jenkins:
    image: jenkins/jenkins:2.319.3-lts
    container_name: jenkins
    restart: unless-stopped 
    environment:
      JAVA_OPTS: "-Dorg.apache.commons.jelly.tags.fmt.timeZone='Asia/Shanghai'"
    volumes:
      - /opt/jenkins:/var/jenkins_home
    ports:
      - "8080:8080"
      - "50000:50000"
    privileged: true
