version: '3.7'

services:
  db:
    image: mysql:5.7.18
    container_name: mysql
    restart: always
    volumes:
      - ./database:/var/lib/mysql
      - ./config/my.cnf:/etc/my.cnf
      - ./init:/docker-entrypoint-initdb.d/
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
volumes:
  data:
    driver: local
