version: '3.7'

services:
  reverse-proxy:
    image: traefik:1.7-alpine
    command: --api --docker
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./acme.json:/acme.json
    labels:
      - "traefik.port=8080"
      - "traefik.backend=reverse-proxy"
      - "traefik.frontend.rule=Host:traefik.domain.com"
      - "traefik.enable=true"
      - "traefik.frontend.auth.basic=user:password"

  whoami:
    image: emilevauge/whoami
    labels:
      - "traefik.frontend.rule=Host:whoami.domain.com"
