version: '3.7'

services:
  whoami:
    image: emilevauge/whoami:latest
    container_name: whoami
    restart: always
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.whoami-secure.entrypoints=websecure"
      - "traefik.http.routers.whoami-secure.rule=Host(`whoami.domain.com`)"
      - "traefik.http.services.whoami-secure.loadbalancer.server.port=80"

networks:
  proxy:
    external: true
